version: "2"
linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - gocritic
    - godox
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - whitespace
  settings:
    depguard:
      rules:
        Main:
          files:
            - "$all"
            - "!$test"
          allow:
            - $gostd
            - github.com/apex/log
            - github.com/apex/log/handlers/cli
            - github.com/kyoh86/gimedic/app
            - github.com/kyoh86/gimedic/internal/scheduler
            - github.com/kyoh86/gimedic/internal/syncer
            - github.com/kyoh86/gimedic
            - github.com/spf13/cobra
            - google.golang.org/protobuf/proto
        Tests:
          files:
            - "$test"
          allow:
            - $gostd
            - github.com/kyoh86/gimedic
            - github.com/kyoh86/gimedic/internal/syncer
            - github.com/spf13/cobra
            - google.golang.org/protobuf/proto
    gocritic:
      disabled-checks:
        - elseif
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
