# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2
project_name: gimedic
builds:
  - id: default
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - "386"
    main: ./cmd/gimedic
    binary: gimedic
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    hooks:
      post:
        - go run -tags man -ldflags "-X=main.version={{.Version}} -X=main.commit={{.ShortCommit}} -X=main.date={{.Date}}" ./cmd/gimedic man
nfpms:
  - builds:
      - default
    maintainer: kyoh86 <me@kyoh86.dev>
    homepage: https://github.com/kyoh86/gimedic
    description: ""
    license: MIT
    formats:
      - apk
      - deb
      - rpm
archives:
  - id: gzip
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - licence*
      - LICENCE*
      - license*
      - LICENSE*
      - readme*
      - README*
      - changelog*
      - CHANGELOG*
      - gimedic*.1
