// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: user_dictionary_storage.proto

package gimedic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserDictionary_PosType int32

const (
	UserDictionary_NO_POS                        UserDictionary_PosType = 0  // "品詞なし"
	UserDictionary_NOUN                          UserDictionary_PosType = 1  // "名詞"
	UserDictionary_ABBREVIATION                  UserDictionary_PosType = 2  // "短縮よみ"
	UserDictionary_SUGGESTION_ONLY               UserDictionary_PosType = 3  // "サジェストのみ"
	UserDictionary_PROPER_NOUN                   UserDictionary_PosType = 4  // "固有名詞"
	UserDictionary_PERSONAL_NAME                 UserDictionary_PosType = 5  // "人名"
	UserDictionary_FAMILY_NAME                   UserDictionary_PosType = 6  // "姓"
	UserDictionary_FIRST_NAME                    UserDictionary_PosType = 7  // "名"
	UserDictionary_ORGANIZATION_NAME             UserDictionary_PosType = 8  // "組織"
	UserDictionary_PLACE_NAME                    UserDictionary_PosType = 9  // "地名"
	UserDictionary_SA_IRREGULAR_CONJUGATION_NOUN UserDictionary_PosType = 10 // "名詞サ変"
	UserDictionary_ADJECTIVE_VERBAL_NOUN         UserDictionary_PosType = 11 // "名詞形動"
	UserDictionary_NUMBER                        UserDictionary_PosType = 12 // "数"
	UserDictionary_ALPHABET                      UserDictionary_PosType = 13 // "アルファベット"
	UserDictionary_SYMBOL                        UserDictionary_PosType = 14 // "記号"
	UserDictionary_EMOTICON                      UserDictionary_PosType = 15 // "顔文字"
	UserDictionary_ADVERB                        UserDictionary_PosType = 16 // "副詞"
	UserDictionary_PRENOUN_ADJECTIVAL            UserDictionary_PosType = 17 // "連体詞"
	UserDictionary_CONJUNCTION                   UserDictionary_PosType = 18 // "接続詞"
	UserDictionary_INTERJECTION                  UserDictionary_PosType = 19 // "感動詞"
	UserDictionary_PREFIX                        UserDictionary_PosType = 20 // "接頭語"
	UserDictionary_COUNTER_SUFFIX                UserDictionary_PosType = 21 // "助数詞"
	UserDictionary_GENERIC_SUFFIX                UserDictionary_PosType = 22 // "接尾一般"
	UserDictionary_PERSON_NAME_SUFFIX            UserDictionary_PosType = 23 // "接尾人名"
	UserDictionary_PLACE_NAME_SUFFIX             UserDictionary_PosType = 24 // "接尾地名"
	UserDictionary_WA_GROUP1_VERB                UserDictionary_PosType = 25 // "動詞ワ行五段"
	UserDictionary_KA_GROUP1_VERB                UserDictionary_PosType = 26 // "動詞カ行五段"
	UserDictionary_SA_GROUP1_VERB                UserDictionary_PosType = 27 // "動詞サ行五段"
	UserDictionary_TA_GROUP1_VERB                UserDictionary_PosType = 28 // "動詞タ行五段"
	UserDictionary_NA_GROUP1_VERB                UserDictionary_PosType = 29 // "動詞ナ行五段"
	UserDictionary_MA_GROUP1_VERB                UserDictionary_PosType = 30 // "動詞マ行五段"
	UserDictionary_RA_GROUP1_VERB                UserDictionary_PosType = 31 // "動詞ラ行五段"
	UserDictionary_GA_GROUP1_VERB                UserDictionary_PosType = 32 // "動詞ガ行五段"
	UserDictionary_BA_GROUP1_VERB                UserDictionary_PosType = 33 // "動詞バ行五段"
	UserDictionary_HA_GROUP1_VERB                UserDictionary_PosType = 34 // "動詞ハ行四段"
	UserDictionary_GROUP2_VERB                   UserDictionary_PosType = 35 // "動詞一段"
	UserDictionary_KURU_GROUP3_VERB              UserDictionary_PosType = 36 // "動詞カ変"
	UserDictionary_SURU_GROUP3_VERB              UserDictionary_PosType = 37 // "動詞サ変"
	UserDictionary_ZURU_GROUP3_VERB              UserDictionary_PosType = 38 // "動詞ザ変"
	UserDictionary_RU_GROUP3_VERB                UserDictionary_PosType = 39 // "動詞ラ変"
	UserDictionary_ADJECTIVE                     UserDictionary_PosType = 40 // "形容詞"
	UserDictionary_SENTENCE_ENDING_PARTICLE      UserDictionary_PosType = 41 // "終助詞"
	UserDictionary_PUNCTUATION                   UserDictionary_PosType = 42 // "句読点"
	UserDictionary_FREE_STANDING_WORD            UserDictionary_PosType = 43 // "独立語"
	UserDictionary_SUPPRESSION_WORD              UserDictionary_PosType = 44 // "抑制単語"
)

// Enum value maps for UserDictionary_PosType.
var (
	UserDictionary_PosType_name = map[int32]string{
		0:  "NO_POS",
		1:  "NOUN",
		2:  "ABBREVIATION",
		3:  "SUGGESTION_ONLY",
		4:  "PROPER_NOUN",
		5:  "PERSONAL_NAME",
		6:  "FAMILY_NAME",
		7:  "FIRST_NAME",
		8:  "ORGANIZATION_NAME",
		9:  "PLACE_NAME",
		10: "SA_IRREGULAR_CONJUGATION_NOUN",
		11: "ADJECTIVE_VERBAL_NOUN",
		12: "NUMBER",
		13: "ALPHABET",
		14: "SYMBOL",
		15: "EMOTICON",
		16: "ADVERB",
		17: "PRENOUN_ADJECTIVAL",
		18: "CONJUNCTION",
		19: "INTERJECTION",
		20: "PREFIX",
		21: "COUNTER_SUFFIX",
		22: "GENERIC_SUFFIX",
		23: "PERSON_NAME_SUFFIX",
		24: "PLACE_NAME_SUFFIX",
		25: "WA_GROUP1_VERB",
		26: "KA_GROUP1_VERB",
		27: "SA_GROUP1_VERB",
		28: "TA_GROUP1_VERB",
		29: "NA_GROUP1_VERB",
		30: "MA_GROUP1_VERB",
		31: "RA_GROUP1_VERB",
		32: "GA_GROUP1_VERB",
		33: "BA_GROUP1_VERB",
		34: "HA_GROUP1_VERB",
		35: "GROUP2_VERB",
		36: "KURU_GROUP3_VERB",
		37: "SURU_GROUP3_VERB",
		38: "ZURU_GROUP3_VERB",
		39: "RU_GROUP3_VERB",
		40: "ADJECTIVE",
		41: "SENTENCE_ENDING_PARTICLE",
		42: "PUNCTUATION",
		43: "FREE_STANDING_WORD",
		44: "SUPPRESSION_WORD",
	}
	UserDictionary_PosType_value = map[string]int32{
		"NO_POS":                        0,
		"NOUN":                          1,
		"ABBREVIATION":                  2,
		"SUGGESTION_ONLY":               3,
		"PROPER_NOUN":                   4,
		"PERSONAL_NAME":                 5,
		"FAMILY_NAME":                   6,
		"FIRST_NAME":                    7,
		"ORGANIZATION_NAME":             8,
		"PLACE_NAME":                    9,
		"SA_IRREGULAR_CONJUGATION_NOUN": 10,
		"ADJECTIVE_VERBAL_NOUN":         11,
		"NUMBER":                        12,
		"ALPHABET":                      13,
		"SYMBOL":                        14,
		"EMOTICON":                      15,
		"ADVERB":                        16,
		"PRENOUN_ADJECTIVAL":            17,
		"CONJUNCTION":                   18,
		"INTERJECTION":                  19,
		"PREFIX":                        20,
		"COUNTER_SUFFIX":                21,
		"GENERIC_SUFFIX":                22,
		"PERSON_NAME_SUFFIX":            23,
		"PLACE_NAME_SUFFIX":             24,
		"WA_GROUP1_VERB":                25,
		"KA_GROUP1_VERB":                26,
		"SA_GROUP1_VERB":                27,
		"TA_GROUP1_VERB":                28,
		"NA_GROUP1_VERB":                29,
		"MA_GROUP1_VERB":                30,
		"RA_GROUP1_VERB":                31,
		"GA_GROUP1_VERB":                32,
		"BA_GROUP1_VERB":                33,
		"HA_GROUP1_VERB":                34,
		"GROUP2_VERB":                   35,
		"KURU_GROUP3_VERB":              36,
		"SURU_GROUP3_VERB":              37,
		"ZURU_GROUP3_VERB":              38,
		"RU_GROUP3_VERB":                39,
		"ADJECTIVE":                     40,
		"SENTENCE_ENDING_PARTICLE":      41,
		"PUNCTUATION":                   42,
		"FREE_STANDING_WORD":            43,
		"SUPPRESSION_WORD":              44,
	}
)

func (x UserDictionary_PosType) Enum() *UserDictionary_PosType {
	p := new(UserDictionary_PosType)
	*p = x
	return p
}

func (x UserDictionary_PosType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserDictionary_PosType) Descriptor() protoreflect.EnumDescriptor {
	return file_user_dictionary_storage_proto_enumTypes[0].Descriptor()
}

func (UserDictionary_PosType) Type() protoreflect.EnumType {
	return &file_user_dictionary_storage_proto_enumTypes[0]
}

func (x UserDictionary_PosType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *UserDictionary_PosType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = UserDictionary_PosType(num)
	return nil
}

// Deprecated: Use UserDictionary_PosType.Descriptor instead.
func (UserDictionary_PosType) EnumDescriptor() ([]byte, []int) {
	return file_user_dictionary_storage_proto_rawDescGZIP(), []int{0, 0}
}

type UserDictionary struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            *uint64                 `protobuf:"varint,1,opt,name=id,def=0" json:"id,omitempty"`
	Name          *string                 `protobuf:"bytes,3,opt,name=name,def=" json:"name,omitempty"`
	Entries       []*UserDictionary_Entry `protobuf:"bytes,4,rep,name=entries" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for UserDictionary fields.
const (
	Default_UserDictionary_Id   = uint64(0)
	Default_UserDictionary_Name = string("")
)

func (x *UserDictionary) Reset() {
	*x = UserDictionary{}
	mi := &file_user_dictionary_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDictionary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDictionary) ProtoMessage() {}

func (x *UserDictionary) ProtoReflect() protoreflect.Message {
	mi := &file_user_dictionary_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDictionary.ProtoReflect.Descriptor instead.
func (*UserDictionary) Descriptor() ([]byte, []int) {
	return file_user_dictionary_storage_proto_rawDescGZIP(), []int{0}
}

func (x *UserDictionary) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_UserDictionary_Id
}

func (x *UserDictionary) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return Default_UserDictionary_Name
}

func (x *UserDictionary) GetEntries() []*UserDictionary_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type UserDictionaryStorage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *int32                 `protobuf:"varint,1,opt,name=version,def=0" json:"version,omitempty"`
	Dictionaries  []*UserDictionary      `protobuf:"bytes,2,rep,name=dictionaries" json:"dictionaries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for UserDictionaryStorage fields.
const (
	Default_UserDictionaryStorage_Version = int32(0)
)

func (x *UserDictionaryStorage) Reset() {
	*x = UserDictionaryStorage{}
	mi := &file_user_dictionary_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDictionaryStorage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDictionaryStorage) ProtoMessage() {}

func (x *UserDictionaryStorage) ProtoReflect() protoreflect.Message {
	mi := &file_user_dictionary_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDictionaryStorage.ProtoReflect.Descriptor instead.
func (*UserDictionaryStorage) Descriptor() ([]byte, []int) {
	return file_user_dictionary_storage_proto_rawDescGZIP(), []int{1}
}

func (x *UserDictionaryStorage) GetVersion() int32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return Default_UserDictionaryStorage_Version
}

func (x *UserDictionaryStorage) GetDictionaries() []*UserDictionary {
	if x != nil {
		return x.Dictionaries
	}
	return nil
}

type UserDictionary_Entry struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Key           *string                 `protobuf:"bytes,1,opt,name=key,def=" json:"key,omitempty"`
	Value         *string                 `protobuf:"bytes,2,opt,name=value,def=" json:"value,omitempty"`
	Comment       *string                 `protobuf:"bytes,4,opt,name=comment,def=" json:"comment,omitempty"`
	Pos           *UserDictionary_PosType `protobuf:"varint,5,opt,name=pos,enum=mozc.user_dictionary.UserDictionary_PosType,def=1" json:"pos,omitempty"`
	Locale        *string                 `protobuf:"bytes,12,opt,name=locale,def=" json:"locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for UserDictionary_Entry fields.
const (
	Default_UserDictionary_Entry_Key     = string("")
	Default_UserDictionary_Entry_Value   = string("")
	Default_UserDictionary_Entry_Comment = string("")
	Default_UserDictionary_Entry_Pos     = UserDictionary_NOUN
	Default_UserDictionary_Entry_Locale  = string("")
)

func (x *UserDictionary_Entry) Reset() {
	*x = UserDictionary_Entry{}
	mi := &file_user_dictionary_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDictionary_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDictionary_Entry) ProtoMessage() {}

func (x *UserDictionary_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_user_dictionary_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDictionary_Entry.ProtoReflect.Descriptor instead.
func (*UserDictionary_Entry) Descriptor() ([]byte, []int) {
	return file_user_dictionary_storage_proto_rawDescGZIP(), []int{0, 0}
}

func (x *UserDictionary_Entry) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return Default_UserDictionary_Entry_Key
}

func (x *UserDictionary_Entry) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return Default_UserDictionary_Entry_Value
}

func (x *UserDictionary_Entry) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return Default_UserDictionary_Entry_Comment
}

func (x *UserDictionary_Entry) GetPos() UserDictionary_PosType {
	if x != nil && x.Pos != nil {
		return *x.Pos
	}
	return Default_UserDictionary_Entry_Pos
}

func (x *UserDictionary_Entry) GetLocale() string {
	if x != nil && x.Locale != nil {
		return *x.Locale
	}
	return Default_UserDictionary_Entry_Locale
}

var File_user_dictionary_storage_proto protoreflect.FileDescriptor

const file_user_dictionary_storage_proto_rawDesc = "" +
	"\n" +
	"\x1duser_dictionary_storage.proto\x12\x14mozc.user_dictionary\"\xa3\t\n" +
	"\x0eUserDictionary\x12\x11\n" +
	"\x02id\x18\x01 \x01(\x04:\x010R\x02id\x12\x14\n" +
	"\x04name\x18\x03 \x01(\t:\x00R\x04name\x12D\n" +
	"\aentries\x18\x04 \x03(\v2*.mozc.user_dictionary.UserDictionary.EntryR\aentries\x1a\xb5\x01\n" +
	"\x05Entry\x12\x12\n" +
	"\x03key\x18\x01 \x01(\t:\x00R\x03key\x12\x16\n" +
	"\x05value\x18\x02 \x01(\t:\x00R\x05value\x12\x1a\n" +
	"\acomment\x18\x04 \x01(\t:\x00R\acomment\x12D\n" +
	"\x03pos\x18\x05 \x01(\x0e2,.mozc.user_dictionary.UserDictionary.PosType:\x04NOUNR\x03pos\x12\x18\n" +
	"\x06locale\x18\f \x01(\t:\x00R\x06localeJ\x04\b\x03\x10\x04\"\xe9\x06\n" +
	"\aPosType\x12\n" +
	"\n" +
	"\x06NO_POS\x10\x00\x12\b\n" +
	"\x04NOUN\x10\x01\x12\x10\n" +
	"\fABBREVIATION\x10\x02\x12\x13\n" +
	"\x0fSUGGESTION_ONLY\x10\x03\x12\x0f\n" +
	"\vPROPER_NOUN\x10\x04\x12\x11\n" +
	"\rPERSONAL_NAME\x10\x05\x12\x0f\n" +
	"\vFAMILY_NAME\x10\x06\x12\x0e\n" +
	"\n" +
	"FIRST_NAME\x10\a\x12\x15\n" +
	"\x11ORGANIZATION_NAME\x10\b\x12\x0e\n" +
	"\n" +
	"PLACE_NAME\x10\t\x12!\n" +
	"\x1dSA_IRREGULAR_CONJUGATION_NOUN\x10\n" +
	"\x12\x19\n" +
	"\x15ADJECTIVE_VERBAL_NOUN\x10\v\x12\n" +
	"\n" +
	"\x06NUMBER\x10\f\x12\f\n" +
	"\bALPHABET\x10\r\x12\n" +
	"\n" +
	"\x06SYMBOL\x10\x0e\x12\f\n" +
	"\bEMOTICON\x10\x0f\x12\n" +
	"\n" +
	"\x06ADVERB\x10\x10\x12\x16\n" +
	"\x12PRENOUN_ADJECTIVAL\x10\x11\x12\x0f\n" +
	"\vCONJUNCTION\x10\x12\x12\x10\n" +
	"\fINTERJECTION\x10\x13\x12\n" +
	"\n" +
	"\x06PREFIX\x10\x14\x12\x12\n" +
	"\x0eCOUNTER_SUFFIX\x10\x15\x12\x12\n" +
	"\x0eGENERIC_SUFFIX\x10\x16\x12\x16\n" +
	"\x12PERSON_NAME_SUFFIX\x10\x17\x12\x15\n" +
	"\x11PLACE_NAME_SUFFIX\x10\x18\x12\x12\n" +
	"\x0eWA_GROUP1_VERB\x10\x19\x12\x12\n" +
	"\x0eKA_GROUP1_VERB\x10\x1a\x12\x12\n" +
	"\x0eSA_GROUP1_VERB\x10\x1b\x12\x12\n" +
	"\x0eTA_GROUP1_VERB\x10\x1c\x12\x12\n" +
	"\x0eNA_GROUP1_VERB\x10\x1d\x12\x12\n" +
	"\x0eMA_GROUP1_VERB\x10\x1e\x12\x12\n" +
	"\x0eRA_GROUP1_VERB\x10\x1f\x12\x12\n" +
	"\x0eGA_GROUP1_VERB\x10 \x12\x12\n" +
	"\x0eBA_GROUP1_VERB\x10!\x12\x12\n" +
	"\x0eHA_GROUP1_VERB\x10\"\x12\x0f\n" +
	"\vGROUP2_VERB\x10#\x12\x14\n" +
	"\x10KURU_GROUP3_VERB\x10$\x12\x14\n" +
	"\x10SURU_GROUP3_VERB\x10%\x12\x14\n" +
	"\x10ZURU_GROUP3_VERB\x10&\x12\x12\n" +
	"\x0eRU_GROUP3_VERB\x10'\x12\r\n" +
	"\tADJECTIVE\x10(\x12\x1c\n" +
	"\x18SENTENCE_ENDING_PARTICLE\x10)\x12\x0f\n" +
	"\vPUNCTUATION\x10*\x12\x16\n" +
	"\x12FREE_STANDING_WORD\x10+\x12\x14\n" +
	"\x10SUPPRESSION_WORD\x10,\"~\n" +
	"\x15UserDictionaryStorage\x12\x1b\n" +
	"\aversion\x18\x01 \x01(\x05:\x010R\aversion\x12H\n" +
	"\fdictionaries\x18\x02 \x03(\v2$.mozc.user_dictionary.UserDictionaryR\fdictionariesB\x1bZ\x19github.com/kyoh86/gimedic"

var (
	file_user_dictionary_storage_proto_rawDescOnce sync.Once
	file_user_dictionary_storage_proto_rawDescData []byte
)

func file_user_dictionary_storage_proto_rawDescGZIP() []byte {
	file_user_dictionary_storage_proto_rawDescOnce.Do(func() {
		file_user_dictionary_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_dictionary_storage_proto_rawDesc), len(file_user_dictionary_storage_proto_rawDesc)))
	})
	return file_user_dictionary_storage_proto_rawDescData
}

var file_user_dictionary_storage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_dictionary_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_user_dictionary_storage_proto_goTypes = []any{
	(UserDictionary_PosType)(0),   // 0: mozc.user_dictionary.UserDictionary.PosType
	(*UserDictionary)(nil),        // 1: mozc.user_dictionary.UserDictionary
	(*UserDictionaryStorage)(nil), // 2: mozc.user_dictionary.UserDictionaryStorage
	(*UserDictionary_Entry)(nil),  // 3: mozc.user_dictionary.UserDictionary.Entry
}
var file_user_dictionary_storage_proto_depIdxs = []int32{
	3, // 0: mozc.user_dictionary.UserDictionary.entries:type_name -> mozc.user_dictionary.UserDictionary.Entry
	1, // 1: mozc.user_dictionary.UserDictionaryStorage.dictionaries:type_name -> mozc.user_dictionary.UserDictionary
	0, // 2: mozc.user_dictionary.UserDictionary.Entry.pos:type_name -> mozc.user_dictionary.UserDictionary.PosType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_user_dictionary_storage_proto_init() }
func file_user_dictionary_storage_proto_init() {
	if File_user_dictionary_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_dictionary_storage_proto_rawDesc), len(file_user_dictionary_storage_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_dictionary_storage_proto_goTypes,
		DependencyIndexes: file_user_dictionary_storage_proto_depIdxs,
		EnumInfos:         file_user_dictionary_storage_proto_enumTypes,
		MessageInfos:      file_user_dictionary_storage_proto_msgTypes,
	}.Build()
	File_user_dictionary_storage_proto = out.File
	file_user_dictionary_storage_proto_goTypes = nil
	file_user_dictionary_storage_proto_depIdxs = nil
}
